-- ══════════════════════════════════════════════════════
-- BooMondai — Schema V2 (Complete Fresh Init)
-- Source of truth: Dart DTOs in lib/models/dtos/
-- dart_mappable configured with snake_case → all columns snake_case.
-- profiles.id is a local UUID; profiles.user_id is the auth.users FK.
-- ══════════════════════════════════════════════════════

-- ── Extensions ────────────────────────────────────────
CREATE EXTENSION IF NOT EXISTS moddatetime SCHEMA extensions;

-- ══════════════════════════════════════════════════════
-- ENUMS
-- ══════════════════════════════════════════════════════

-- Matches StudyRating Dart enum in drill_answer.dto.dart
CREATE TYPE study_rating AS ENUM ('incorrect', 'again', 'hard', 'good', 'easy');

-- Matches CardType Dart enum in card_type.dto.dart
-- Controls how many ReviewCards a FlashcardTemplate generates.
CREATE TYPE card_type AS ENUM ('normal', 'reversed', 'both');

-- ══════════════════════════════════════════════════════
-- CORE TABLES
-- ══════════════════════════════════════════════════════

-- ── profiles ──────────────────────────────────────────
-- id        = local app UUID (generated by client or backend)
-- user_id   = FK to auth.users (always non-null; backend creates the row)
-- No email column — email lives in auth.users only.
-- No updated_at — not in the Profile DTO.
CREATE TABLE profiles (
  id              uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id         uuid NOT NULL UNIQUE REFERENCES auth.users(id) ON DELETE CASCADE,
  username        text NOT NULL,
  role            text NOT NULL DEFAULT 'group_a_participant'
                  CHECK (role IN ('group_a_participant', 'group_b_participant', 'researcher')),
  avatar_url      text,
  target_language text,
  created_at      timestamptz NOT NULL DEFAULT now(),
  updated_at      timestamptz NOT NULL DEFAULT now()
);
ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;
-- Everyone can read profiles (leaderboard, attribution, etc.)
CREATE POLICY "profiles: read all" ON profiles FOR SELECT USING (true);
-- Users may only update their own profile row.
CREATE POLICY "profiles: update own" ON profiles FOR UPDATE
  USING     ((select auth.uid()) = user_id)
  WITH CHECK ((select auth.uid()) = user_id);
-- INSERT is handled by the backend via service role — no user-level insert policy.
CREATE INDEX ON profiles (user_id);

-- ── Helper: resolve auth.uid() → profiles.id ─────────
-- Used throughout RLS policies. SECURITY DEFINER so it can always read profiles
-- even when called from within an RLS expression.
CREATE OR REPLACE FUNCTION current_profile_id()
RETURNS uuid
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT id FROM profiles WHERE user_id = (select auth.uid()) LIMIT 1
$$;

-- ── decks ─────────────────────────────────────────────
-- user_id references profiles.id (the local UUID, not auth UUID).
-- is_editable replaces the old is_uneditable (logic inverted: true = editable).
-- No source_author_id, no hidden_in_browser — not in Deck DTO.
CREATE TABLE decks (
  id                uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id           uuid NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  title             text NOT NULL,
  short_description text NOT NULL DEFAULT '',
  long_description  text NOT NULL DEFAULT '',
  target_language   text NOT NULL,
  tags              text[] NOT NULL DEFAULT '{}',
  is_premade        bool NOT NULL DEFAULT false,
  is_public         bool NOT NULL DEFAULT true,
  is_published      bool NOT NULL DEFAULT false,
  is_editable       bool NOT NULL DEFAULT true,
  card_count        int  NOT NULL DEFAULT 0,
  version           text NOT NULL DEFAULT '1.0.0',
  build_number      int  NOT NULL DEFAULT 1,
  source_deck_id    uuid REFERENCES decks(id) ON DELETE SET NULL,
  created_at        timestamptz NOT NULL DEFAULT now(),
  updated_at        timestamptz NOT NULL DEFAULT now()
);
ALTER TABLE decks ENABLE ROW LEVEL SECURITY;
CREATE POLICY "decks: read public or own" ON decks FOR SELECT
  USING (is_public = true OR user_id = current_profile_id());
CREATE POLICY "decks: owner insert" ON decks FOR INSERT
  WITH CHECK (user_id = current_profile_id());
CREATE POLICY "decks: owner update" ON decks FOR UPDATE
  USING     (user_id = current_profile_id())
  WITH CHECK (user_id = current_profile_id());
CREATE POLICY "decks: owner delete" ON decks FOR DELETE
  USING (user_id = current_profile_id());
CREATE INDEX ON decks (user_id);
CREATE INDEX ON decks (target_language);
CREATE INDEX ON decks (is_public);
CREATE INDEX ON decks (source_deck_id);
CREATE INDEX ON decks USING gin (tags);
CREATE TRIGGER set_updated_at BEFORE UPDATE ON decks
  FOR EACH ROW EXECUTE FUNCTION moddatetime(updated_at);

-- ── card_templates ────────────────────────────────────
-- Wide table: all subclass-specific fields are nullable columns.
-- The `type` discriminator tells dart_mappable which subclass to use.
--
-- Column ownership by subclass:
--
--   flashcard:          front_text, back_text,
--                       front_image_url, back_image_url,
--                       front_audio_url, back_audio_url,
--                       card_type
--
--   identification:     prompt_text, accepted_answers,
--                       image_url, audio_url
--
--   multiple_choice:    question_prompt,
--                       image_url, audio_url
--
--   word_scramble:      sentence_to_scramble,
--                       image_url, audio_url
--
--   fill_in_the_blanks: (content in fill_in_the_blank_segments table)
--   match_madness:      (content in match_madness_pairs table)
CREATE TABLE card_templates (
  -- ── base CardTemplate fields ──────────────────
  id                   uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  deck_id              uuid NOT NULL REFERENCES decks(id) ON DELETE CASCADE,
  type                 text NOT NULL
                       CHECK (type IN (
                         'flashcard', 'identification', 'multiple_choice',
                         'fill_in_the_blanks', 'word_scramble', 'match_madness'
                       )),
  sort_order           int  NOT NULL DEFAULT 0,
  source_template_id   uuid REFERENCES card_templates(id) ON DELETE SET NULL,
  created_at           timestamptz NOT NULL DEFAULT now(),
  updated_at           timestamptz NOT NULL DEFAULT now(),

  -- ── FlashcardTemplate ─────────────────────────
  front_text           text,
  back_text            text,
  front_image_url      text,
  back_image_url       text,
  front_audio_url      text,
  back_audio_url       text,
  card_type            card_type,      -- normal | reversed | both

  -- ── IdentificationTemplate ────────────────────
  prompt_text          text,
  accepted_answers     text,           -- comma-separated accepted answers

  -- ── MultipleChoiceTemplate ────────────────────
  question_prompt      text,

  -- ── WordScrambleTemplate ──────────────────────
  sentence_to_scramble text,

  -- ── Shared: identification, multiple_choice, word_scramble ──
  image_url            text,
  audio_url            text
);
ALTER TABLE card_templates ENABLE ROW LEVEL SECURITY;
CREATE POLICY "card_templates: read if deck accessible" ON card_templates FOR SELECT
  USING (EXISTS (
    SELECT 1 FROM decks
    WHERE decks.id = card_templates.deck_id
      AND (decks.is_public = true OR decks.user_id = current_profile_id())
  ));
CREATE POLICY "card_templates: owner insert" ON card_templates FOR INSERT
  WITH CHECK (EXISTS (
    SELECT 1 FROM decks
    WHERE decks.id = card_templates.deck_id AND decks.user_id = current_profile_id()
  ));
CREATE POLICY "card_templates: owner update" ON card_templates FOR UPDATE
  USING (EXISTS (
    SELECT 1 FROM decks
    WHERE decks.id = card_templates.deck_id AND decks.user_id = current_profile_id()
  ))
  WITH CHECK (EXISTS (
    SELECT 1 FROM decks
    WHERE decks.id = card_templates.deck_id AND decks.user_id = current_profile_id()
  ));
CREATE POLICY "card_templates: owner delete" ON card_templates FOR DELETE
  USING (EXISTS (
    SELECT 1 FROM decks
    WHERE decks.id = card_templates.deck_id AND decks.user_id = current_profile_id()
  ));
CREATE INDEX ON card_templates (deck_id);
CREATE INDEX ON card_templates (source_template_id);
CREATE TRIGGER set_updated_at BEFORE UPDATE ON card_templates
  FOR EACH ROW EXECUTE FUNCTION moddatetime(updated_at);

-- ── multiple_choice_options ───────────────────────────
-- Maps to MultipleChoiceOption DTO.
-- template_id = FK to card_templates (DTO field: templateId → snake: template_id)
CREATE TABLE multiple_choice_options (
  id            uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  template_id   uuid NOT NULL REFERENCES card_templates(id) ON DELETE CASCADE,
  option_text   text NOT NULL,
  is_correct    bool NOT NULL DEFAULT false,
  display_order int  NOT NULL DEFAULT 0
);
ALTER TABLE multiple_choice_options ENABLE ROW LEVEL SECURITY;
CREATE POLICY "multiple_choice_options: read if deck accessible" ON multiple_choice_options FOR SELECT
  USING (EXISTS (
    SELECT 1 FROM card_templates ct JOIN decks d ON d.id = ct.deck_id
    WHERE ct.id = multiple_choice_options.template_id
      AND (d.is_public = true OR d.user_id = current_profile_id())
  ));
CREATE POLICY "multiple_choice_options: owner insert" ON multiple_choice_options FOR INSERT
  WITH CHECK (EXISTS (
    SELECT 1 FROM card_templates ct JOIN decks d ON d.id = ct.deck_id
    WHERE ct.id = multiple_choice_options.template_id AND d.user_id = current_profile_id()
  ));
CREATE POLICY "multiple_choice_options: owner update" ON multiple_choice_options FOR UPDATE
  USING (EXISTS (
    SELECT 1 FROM card_templates ct JOIN decks d ON d.id = ct.deck_id
    WHERE ct.id = multiple_choice_options.template_id AND d.user_id = current_profile_id()
  ))
  WITH CHECK (EXISTS (
    SELECT 1 FROM card_templates ct JOIN decks d ON d.id = ct.deck_id
    WHERE ct.id = multiple_choice_options.template_id AND d.user_id = current_profile_id()
  ));
CREATE POLICY "multiple_choice_options: owner delete" ON multiple_choice_options FOR DELETE
  USING (EXISTS (
    SELECT 1 FROM card_templates ct JOIN decks d ON d.id = ct.deck_id
    WHERE ct.id = multiple_choice_options.template_id AND d.user_id = current_profile_id()
  ));
CREATE INDEX ON multiple_choice_options (template_id);

-- ── fill_in_the_blank_segments ────────────────────────
-- Maps to FillInTheBlankSegment DTO.
-- card_id = FK to card_templates (DTO field name: cardId → snake: card_id)
CREATE TABLE fill_in_the_blank_segments (
  id             uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  card_id        uuid NOT NULL REFERENCES card_templates(id) ON DELETE CASCADE,
  full_text      text NOT NULL,
  blank_start    int  NOT NULL,
  blank_end      int  NOT NULL,
  correct_answer text NOT NULL,
  CONSTRAINT fitb_blank_order CHECK (blank_start < blank_end)
);
ALTER TABLE fill_in_the_blank_segments ENABLE ROW LEVEL SECURITY;
CREATE POLICY "fill_in_the_blank_segments: read if deck accessible" ON fill_in_the_blank_segments FOR SELECT
  USING (EXISTS (
    SELECT 1 FROM card_templates ct JOIN decks d ON d.id = ct.deck_id
    WHERE ct.id = fill_in_the_blank_segments.card_id
      AND (d.is_public = true OR d.user_id = current_profile_id())
  ));
CREATE POLICY "fill_in_the_blank_segments: owner insert" ON fill_in_the_blank_segments FOR INSERT
  WITH CHECK (EXISTS (
    SELECT 1 FROM card_templates ct JOIN decks d ON d.id = ct.deck_id
    WHERE ct.id = fill_in_the_blank_segments.card_id AND d.user_id = current_profile_id()
  ));
CREATE POLICY "fill_in_the_blank_segments: owner update" ON fill_in_the_blank_segments FOR UPDATE
  USING (EXISTS (
    SELECT 1 FROM card_templates ct JOIN decks d ON d.id = ct.deck_id
    WHERE ct.id = fill_in_the_blank_segments.card_id AND d.user_id = current_profile_id()
  ))
  WITH CHECK (EXISTS (
    SELECT 1 FROM card_templates ct JOIN decks d ON d.id = ct.deck_id
    WHERE ct.id = fill_in_the_blank_segments.card_id AND d.user_id = current_profile_id()
  ));
CREATE POLICY "fill_in_the_blank_segments: owner delete" ON fill_in_the_blank_segments FOR DELETE
  USING (EXISTS (
    SELECT 1 FROM card_templates ct JOIN decks d ON d.id = ct.deck_id
    WHERE ct.id = fill_in_the_blank_segments.card_id AND d.user_id = current_profile_id()
  ));
CREATE INDEX ON fill_in_the_blank_segments (card_id);

-- ── match_madness_pairs ───────────────────────────────
-- Maps to MatchMadnessPair DTO.
-- template_id       (DTO: templateId)
-- source_template_id (DTO: sourceTemplateId) — set when pair was auto-picked
CREATE TABLE match_madness_pairs (
  id                 uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  template_id        uuid NOT NULL REFERENCES card_templates(id) ON DELETE CASCADE,
  source_template_id uuid REFERENCES card_templates(id) ON DELETE SET NULL,
  term               text NOT NULL,
  match              text NOT NULL,
  is_auto_picked     bool NOT NULL DEFAULT false,
  display_order      int  NOT NULL DEFAULT 0
);
ALTER TABLE match_madness_pairs ENABLE ROW LEVEL SECURITY;
CREATE POLICY "match_madness_pairs: read if deck accessible" ON match_madness_pairs FOR SELECT
  USING (EXISTS (
    SELECT 1 FROM card_templates ct JOIN decks d ON d.id = ct.deck_id
    WHERE ct.id = match_madness_pairs.template_id
      AND (d.is_public = true OR d.user_id = current_profile_id())
  ));
CREATE POLICY "match_madness_pairs: owner insert" ON match_madness_pairs FOR INSERT
  WITH CHECK (EXISTS (
    SELECT 1 FROM card_templates ct JOIN decks d ON d.id = ct.deck_id
    WHERE ct.id = match_madness_pairs.template_id AND d.user_id = current_profile_id()
  ));
CREATE POLICY "match_madness_pairs: owner update" ON match_madness_pairs FOR UPDATE
  USING (EXISTS (
    SELECT 1 FROM card_templates ct JOIN decks d ON d.id = ct.deck_id
    WHERE ct.id = match_madness_pairs.template_id AND d.user_id = current_profile_id()
  ))
  WITH CHECK (EXISTS (
    SELECT 1 FROM card_templates ct JOIN decks d ON d.id = ct.deck_id
    WHERE ct.id = match_madness_pairs.template_id AND d.user_id = current_profile_id()
  ));
CREATE POLICY "match_madness_pairs: owner delete" ON match_madness_pairs FOR DELETE
  USING (EXISTS (
    SELECT 1 FROM card_templates ct JOIN decks d ON d.id = ct.deck_id
    WHERE ct.id = match_madness_pairs.template_id AND d.user_id = current_profile_id()
  ));
CREATE INDEX ON match_madness_pairs (template_id);
CREATE INDEX ON match_madness_pairs (source_template_id);

-- ── review_cards ──────────────────────────────────────
-- Maps to ReviewCard DTO.
-- One row per reviewable unit per template.
-- is_reversed=false → show front→back (or forward mode)
-- is_reversed=true  → show back→front (reverse mode)
-- UNIQUE constraint ensures at most 2 rows per template (one each direction).
CREATE TABLE review_cards (
  id          uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  template_id uuid NOT NULL REFERENCES card_templates(id) ON DELETE CASCADE,
  is_reversed bool NOT NULL DEFAULT false,
  deck_id     uuid NOT NULL REFERENCES decks(id) ON DELETE CASCADE,
  UNIQUE (template_id, is_reversed)
);
ALTER TABLE review_cards ENABLE ROW LEVEL SECURITY;
CREATE POLICY "review_cards: read if deck accessible" ON review_cards FOR SELECT
  USING (EXISTS (
    SELECT 1 FROM decks
    WHERE decks.id = review_cards.deck_id
      AND (decks.is_public = true OR decks.user_id = current_profile_id())
  ));
CREATE POLICY "review_cards: owner insert" ON review_cards FOR INSERT
  WITH CHECK (EXISTS (
    SELECT 1 FROM decks
    WHERE decks.id = review_cards.deck_id AND decks.user_id = current_profile_id()
  ));
CREATE POLICY "review_cards: owner update" ON review_cards FOR UPDATE
  USING (EXISTS (
    SELECT 1 FROM decks
    WHERE decks.id = review_cards.deck_id AND decks.user_id = current_profile_id()
  ))
  WITH CHECK (EXISTS (
    SELECT 1 FROM decks
    WHERE decks.id = review_cards.deck_id AND decks.user_id = current_profile_id()
  ));
CREATE POLICY "review_cards: owner delete" ON review_cards FOR DELETE
  USING (EXISTS (
    SELECT 1 FROM decks
    WHERE decks.id = review_cards.deck_id AND decks.user_id = current_profile_id()
  ));
CREATE INDEX ON review_cards (template_id);
CREATE INDEX ON review_cards (deck_id);

-- ── drill_sessions ────────────────────────────────────
-- Maps to DrillSession DTO (extends StudySession).
-- session_type = 'drill' (discriminator for dart_mappable).
-- deck_id is nullable (StudySession.deckId is optional).
CREATE TABLE drill_sessions (
  id              uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id         uuid NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  deck_id         uuid REFERENCES decks(id) ON DELETE SET NULL,
  session_type    text NOT NULL DEFAULT 'drill',
  previewed       bool NOT NULL DEFAULT false,
  total_questions int  NOT NULL DEFAULT 0,
  correct_count   int  NOT NULL DEFAULT 0,
  started_at      timestamptz NOT NULL DEFAULT now(),
  completed_at    timestamptz
);
ALTER TABLE drill_sessions ENABLE ROW LEVEL SECURITY;
CREATE POLICY "drill_sessions: owner manages" ON drill_sessions FOR ALL
  USING     (user_id = current_profile_id())
  WITH CHECK (user_id = current_profile_id());
CREATE INDEX ON drill_sessions (user_id);
CREATE INDEX ON drill_sessions (deck_id);

-- ── review_sessions ───────────────────────────────────
-- Maps to ReviewSession DTO (extends StudySession).
-- session_type = 'review' (discriminator for dart_mappable).
CREATE TABLE review_sessions (
  id             uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id        uuid NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  deck_id        uuid REFERENCES decks(id) ON DELETE SET NULL,
  session_type   text NOT NULL DEFAULT 'review',
  total_cards    int  NOT NULL DEFAULT 0,
  cards_reviewed int  NOT NULL DEFAULT 0,
  started_at     timestamptz NOT NULL DEFAULT now(),
  completed_at   timestamptz
);
ALTER TABLE review_sessions ENABLE ROW LEVEL SECURITY;
CREATE POLICY "review_sessions: owner manages" ON review_sessions FOR ALL
  USING     (user_id = current_profile_id())
  WITH CHECK (user_id = current_profile_id());
CREATE INDEX ON review_sessions (user_id);

-- ── drill_answers ─────────────────────────────────────
-- Maps to DrillAnswer DTO.
-- type uses the study_rating enum (StudyRating Dart enum).
-- card_id references card_templates (the blueprint), not review_cards.
CREATE TABLE drill_answers (
  id          uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  session_id  uuid         NOT NULL REFERENCES drill_sessions(id)  ON DELETE CASCADE,
  card_id     uuid         NOT NULL REFERENCES card_templates(id)  ON DELETE CASCADE,
  user_answer text         NOT NULL,
  type        study_rating NOT NULL,
  created_at  timestamptz  NOT NULL DEFAULT now()
);
ALTER TABLE drill_answers ENABLE ROW LEVEL SECURITY;
CREATE POLICY "drill_answers: owner manages" ON drill_answers FOR ALL
  USING (EXISTS (
    SELECT 1 FROM drill_sessions ds
    WHERE ds.id = drill_answers.session_id AND ds.user_id = current_profile_id()
  ))
  WITH CHECK (EXISTS (
    SELECT 1 FROM drill_sessions ds
    WHERE ds.id = drill_answers.session_id AND ds.user_id = current_profile_id()
  ));
CREATE INDEX ON drill_answers (session_id);
CREATE INDEX ON drill_answers (card_id);

-- ── fsrs_cards ────────────────────────────────────────
-- Maps to FsrsCard DTO.
-- user_id references auth.users(id) directly (not profiles.id).
-- state is a JSONB snapshot of the fsrs package's Card object.
-- review_card_id links to the specific ReviewCard being tracked.
CREATE TABLE fsrs_cards (
  id             uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id        uuid NOT NULL REFERENCES auth.users(id)   ON DELETE CASCADE,
  review_card_id uuid NOT NULL REFERENCES review_cards(id) ON DELETE CASCADE,
  state          jsonb NOT NULL DEFAULT '{}',
  created_at     timestamptz NOT NULL DEFAULT now(),
  updated_at     timestamptz NOT NULL DEFAULT now()
);
ALTER TABLE fsrs_cards ENABLE ROW LEVEL SECURITY;
CREATE POLICY "fsrs_cards: owner manages" ON fsrs_cards FOR ALL
  USING     ((select auth.uid()) = user_id)
  WITH CHECK ((select auth.uid()) = user_id);
CREATE INDEX ON fsrs_cards (user_id);
CREATE TRIGGER set_updated_at BEFORE UPDATE ON fsrs_cards
  FOR EACH ROW EXECUTE FUNCTION moddatetime(updated_at);

-- ── review_logs ───────────────────────────────────────
-- Maps to FsrsReviewLog DTO.
-- fsrs_card_id = FK to fsrs_cards (DTO field: fsrsCardId → snake: fsrs_card_id).
-- log is a JSONB snapshot of the fsrs package's ReviewLog object.
-- No user_id column — derivable via fsrs_card_id → fsrs_cards.user_id.
CREATE TABLE review_logs (
  id           uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  fsrs_card_id uuid NOT NULL REFERENCES fsrs_cards(id) ON DELETE CASCADE,
  log          jsonb NOT NULL DEFAULT '{}',
  created_at   timestamptz NOT NULL DEFAULT now()
);
ALTER TABLE review_logs ENABLE ROW LEVEL SECURITY;
CREATE POLICY "review_logs: owner manages" ON review_logs FOR ALL
  USING (EXISTS (
    SELECT 1 FROM fsrs_cards fc
    WHERE fc.id = review_logs.fsrs_card_id AND fc.user_id = (select auth.uid())
  ))
  WITH CHECK (EXISTS (
    SELECT 1 FROM fsrs_cards fc
    WHERE fc.id = review_logs.fsrs_card_id AND fc.user_id = (select auth.uid())
  ));
CREATE INDEX ON review_logs (fsrs_card_id);

-- ── streaks ───────────────────────────────────────────
-- Maps to Streak DTO.
-- Activity definition: completing at least one FSRS review per day.
CREATE TABLE streaks (
  id                 uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id            uuid NOT NULL UNIQUE REFERENCES profiles(id) ON DELETE CASCADE,
  current_streak     int  NOT NULL DEFAULT 0,
  longest_streak     int  NOT NULL DEFAULT 0,
  last_activity_date date,
  created_at         timestamptz NOT NULL DEFAULT now(),
  updated_at         timestamptz NOT NULL DEFAULT now()
);
ALTER TABLE streaks ENABLE ROW LEVEL SECURITY;
CREATE POLICY "streaks: owner manages" ON streaks FOR ALL
  USING     (user_id = current_profile_id())
  WITH CHECK (user_id = current_profile_id());
CREATE INDEX ON streaks (user_id);
CREATE TRIGGER set_updated_at BEFORE UPDATE ON streaks
  FOR EACH ROW EXECUTE FUNCTION moddatetime(updated_at);

-- ── leaderboard (view) ────────────────────────────────
-- Maps to LeaderboardEntry DTO.
-- security_invoker = true → view respects the calling user's RLS.
-- Only group_a_participant profiles appear.
CREATE VIEW leaderboard WITH (security_invoker = true) AS
SELECT
  p.id              AS user_id,
  p.username        AS user_name,
  p.target_language AS target_language,
  COALESCE(SUM(ds.correct_count), 0)::int AS drill_score,
  COALESCE(rc.review_count, 0)::int       AS review_count,
  COALESCE(s.current_streak, 0)           AS current_streak
FROM profiles p
LEFT JOIN drill_sessions ds
  ON ds.user_id = p.id AND ds.completed_at IS NOT NULL
LEFT JOIN (
  SELECT fc.user_id, COUNT(*)::int AS review_count
  FROM review_logs rl
  JOIN fsrs_cards fc ON fc.id = rl.fsrs_card_id
  GROUP BY fc.user_id
) rc ON rc.user_id = p.user_id
LEFT JOIN streaks s ON s.user_id = p.id
WHERE p.role = 'group_a_participant'
GROUP BY p.id, p.username, p.target_language, rc.review_count, s.current_streak
ORDER BY drill_score DESC;

-- ══════════════════════════════════════════════════════
-- RESEARCH TABLES
-- ══════════════════════════════════════════════════════

-- ── research_profiles ────────────────────────────────
-- Maps to ResearchProfile DTO (was research_users).
-- user_id references profiles.id (local UUID).
CREATE TABLE research_profiles (
  id              uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id         uuid NOT NULL UNIQUE REFERENCES profiles(id) ON DELETE CASCADE,
  user_name       text,
  first_name      text NOT NULL DEFAULT '',
  last_name       text NOT NULL DEFAULT '',
  age             int  NOT NULL DEFAULT 0,
  role            text NOT NULL
                  CHECK (role IN ('group_a_participant', 'group_b_participant')),
  target_language text NOT NULL,
  created_at      timestamptz NOT NULL DEFAULT now()
);
ALTER TABLE research_profiles ENABLE ROW LEVEL SECURITY;
-- Researchers manage all research profile records.
CREATE POLICY "research_profiles: researcher manages" ON research_profiles FOR ALL
  USING (EXISTS (
    SELECT 1 FROM profiles WHERE id = current_profile_id() AND role = 'researcher'
  ));
-- Participants may read only their own research profile.
CREATE POLICY "research_profiles: read own" ON research_profiles FOR SELECT
  USING (user_id = current_profile_id());
CREATE INDEX ON research_profiles (user_id);

-- ── research_codes ────────────────────────────────────
-- Maps to ResearchCode DTO.
-- created_by and used_by reference profiles.id (local UUIDs).
CREATE TABLE research_codes (
  id          uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  code        text NOT NULL UNIQUE,
  target_role text NOT NULL,
  unlocks     text NOT NULL,
  created_by  uuid NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  used_by     uuid REFERENCES profiles(id),
  used_at     timestamptz,
  created_at  timestamptz NOT NULL DEFAULT now()
);
ALTER TABLE research_codes ENABLE ROW LEVEL SECURITY;
-- Researchers: full read access.
CREATE POLICY "research_codes: researcher select" ON research_codes FOR SELECT
  USING (EXISTS (
    SELECT 1 FROM profiles WHERE id = current_profile_id() AND role = 'researcher'
  ));
-- Researchers: full write access.
CREATE POLICY "research_codes: researcher insert" ON research_codes FOR INSERT
  WITH CHECK (EXISTS (
    SELECT 1 FROM profiles WHERE id = current_profile_id() AND role = 'researcher'
  ));
CREATE POLICY "research_codes: researcher delete" ON research_codes FOR DELETE
  USING (EXISTS (
    SELECT 1 FROM profiles WHERE id = current_profile_id() AND role = 'researcher'
  ));
-- Participants: read codes they have already redeemed.
CREATE POLICY "research_codes: participant read own" ON research_codes FOR SELECT
  USING (used_by = current_profile_id());
-- Combined UPDATE: participants may claim unclaimed codes; researchers may update any.
CREATE POLICY "research_codes: update" ON research_codes FOR UPDATE
  USING (
    used_by IS NULL
    OR EXISTS (SELECT 1 FROM profiles WHERE id = current_profile_id() AND role = 'researcher')
  )
  WITH CHECK (
    used_by = current_profile_id()
    OR EXISTS (SELECT 1 FROM profiles WHERE id = current_profile_id() AND role = 'researcher')
  );
CREATE INDEX ON research_codes (code);
CREATE INDEX ON research_codes (created_by);

-- ── survey_responses ──────────────────────────────────
-- Maps to SurveyResponse DTO.
-- Replaces all individual per-survey tables.
-- UNIQUE (user_id, survey_type, time_point) prevents duplicate submissions.
-- computed_score is populated for SUS surveys only.
CREATE TABLE survey_responses (
  id              uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id         uuid NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  survey_type     text NOT NULL,
  time_point      text,
  responses       jsonb NOT NULL DEFAULT '{}',
  computed_score  double precision,
  submitted_at    timestamptz NOT NULL DEFAULT now(),
  UNIQUE (user_id, survey_type, time_point)
);
ALTER TABLE survey_responses ENABLE ROW LEVEL SECURITY;
CREATE POLICY "survey_responses: insert own" ON survey_responses FOR INSERT
  WITH CHECK (user_id = current_profile_id());
CREATE POLICY "survey_responses: read own or researcher" ON survey_responses FOR SELECT
  USING (
    user_id = current_profile_id()
    OR EXISTS (SELECT 1 FROM profiles WHERE id = current_profile_id() AND role = 'researcher')
  );
CREATE INDEX ON survey_responses (user_id);
CREATE INDEX ON survey_responses (survey_type);

-- ── vocabulary_test_results ───────────────────────────
-- Maps to VocabularyTestResult DTO (was research_vocabulary_test).
-- test_set: 'A' or 'B'. 30 items each, no overlap.
-- answers: { question_id: selected_option } JSON map.
CREATE TABLE vocabulary_test_results (
  id           uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id      uuid NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  test_set     text NOT NULL CHECK (test_set IN ('A', 'B')),
  score        int  NOT NULL CHECK (score BETWEEN 0 AND 30),
  answers      jsonb NOT NULL,
  submitted_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (user_id, test_set)
);
ALTER TABLE vocabulary_test_results ENABLE ROW LEVEL SECURITY;
CREATE POLICY "vocabulary_test_results: insert own" ON vocabulary_test_results FOR INSERT
  WITH CHECK (user_id = current_profile_id());
CREATE POLICY "vocabulary_test_results: read own or researcher" ON vocabulary_test_results FOR SELECT
  USING (
    user_id = current_profile_id()
    OR EXISTS (SELECT 1 FROM profiles WHERE id = current_profile_id() AND role = 'researcher')
  );
CREATE INDEX ON vocabulary_test_results (user_id);
